#!/bin/bash
yum update -y && \
amazon-linux-extras install -y lamp-mariadb10.2-php7.2 php7.2 && \
yum install -y httpd mariadb-server epel-release && \
systemctl start httpd && \
systemctl enable httpd && \
usermod -a -G apache ec2-user && \
chown -R ec2-user:apache /var/www && \
chmod 2775 /var/www && \
find /var/www -type d -exec chmod 2775 {} \; && \
find /var/www -type f -exec chmod 0664 {} \; && \
echo "<?php phpinfo(); ?>" > /var/www/html/phpinfo.php && \
yum install stress -y && \
INSTANCE_ID="`wget -q -O - http://instance-data/latest/meta-data/instance-id`" && \
aws autoscaling complete-lifecycle-action --lifecycle-action-result CONTINUE --instance-id $INSTANCE_ID --lifecycle-hook-name devops-pro-hook --auto-scaling-group-name DevOps-asg --region us-east-1 || \
aws autoscaling complete-lifecycle-action --lifecycle-action-result ABANDON --instance-id $INSTANCE_ID --lifecycle-hook-name devops-pro-hook --auto-scaling-group-name DevOps-asg --region us-east-1